export const actionTypes = {
    WF_FLAG_API_CALL_REQUEST: 'WF_FLAG_API_CALL_REQUEST',
    WF_FLAG_API_CALL_SUCCESS: 'WF_FLAG_API_CALL_SUCCESS',
    WF_FLAG_API_CALL_FAILURE: 'WF_FLAG_API_CALL_FAILURE',
    API_CALL_REQUEST: 'API_CALL_REQUEST',
    API_CALL_SUCCESS: 'API_CALL_SUCCESS',
    API_CALL_FAILURE: 'API_CALL_FAILURE',
    BOOKMARK_API_CALL_REQUEST: 'BOOKMARK_API_CALL_REQUEST',
    BOOKMARK_API_CALL_SUCCESS: 'BOOKMARK_API_CALL_SUCCESS',
    BOOKMARK_API_CALL_FAILURE: 'BOOKMARK_API_CALL_FAILURE',
    AUD_API_CALL_REQUEST: 'AUD_API_CALL_REQUEST',
    KAKAO_IMG_CALL_REQUEST: 'KAKAO_IMG_CALL_REQUEST',
    KAKAO_IMG_CALL_SUCCESS: 'KAKAO_IMG_CALL_SUCCESS',
    KAKAO_IMG_CALL_FAILURE: 'KAKAO_IMG_CALL_FAILURE',
    MODAL: 'MODAL',
    ERRORHANDLER: 'ERRORHANDLER',
    IMGINPUTREADY: 'IMGINPUTREADY',
    IMGINPUTQUE: 'IMGINPUTQUE',
    TITLE_API_REQUEST: 'TITLE_API_REQUEST',
    TITLE_API_SUCCESS: 'TITLE_API_SUCCESS',
    TITLE_API_FAILURE: 'TITLE_API_FAILURE',
    WF_DATA_API_REQUEST: 'WF_DATA_API_REQUEST',
    WF_DATA_API_SUCCESS: 'WF_DATA_API_SUCCESS',
    WF_DATA_API_FAILURE: 'WF_DATA_API_FAILURE',
    SENDER_CONTENTS_API_REQUEST: 'SENDER_CONTENTS_API_REQUEST',
    SENDER_CONTENTS_API_SUCCESS: 'SENDER_CONTENTS_API_SUCCESS',
    SENDER_CONTENTS_API_FAILURE: 'SENDER_CONTENTS_API_FAILURE'
};

export const actions = {
    MODAL: (flag, modalType, title, contents, size, Fn) => ({
        type: actionTypes.MODAL,
        flag,
        modalType,
        title,
        contents,
        size,
        Fn
    }),
    ERRORHANDLER: flag => ({ type: actionTypes.ERRORHANDLER, flag }),
    IMGINPUTREADY: dom => ({ type: actionTypes.IMGINPUTREADY, dom }),
    IMGINPUTQUE: (dom, url, origin) => ({ type: actionTypes.IMGINPUTQUE, dom, url, origin })
};
